apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-nodejs
  template:
    metadata:
      labels:
        app: devsecops-nodejs
    spec:
      containers:
      - name: nodejs
        image: devsecops-demo:latest
        ports:
        - containerPort: 3000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
